### ISSUE TITLE
Warn users that they'll lose their changes when switching screens.

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/greenup-admin#11]
There currently is not warning that "save" must be clicked before moving to a new town, or user, or whatever.

**Comment by johnneed** [comment]
![image](https://user-images.githubusercontent.com/1043179/55342826-a9e96f00-5477-11e9-9562-0ce10e48e5e5.png)

**Comment by johnneed** [comment]
We should make the save button stand out more, too.

**Comment by tgerade** [comment]
The save button does work, not sure why I didn't notice it.  However, it is impossible to type anything inside existing text.  The cursor goes to the end of the field after each typed letter.
